name = "Neighborhoods"
uuid = "d59d076e-d651-40c5-bb74-151a0352d31d"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.1.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnicodeGraphics = "ebadf6b4-db70-5817-83da-4a19ad584e34"

[compat]
Adapt = "2, 3"
ConstructionBase = "1"
KernelAbstractions = "0.6, 0.7, 0.8"
OffsetArrays = "0.11, 1"
Setfield = "0.6, 0.7, 0.8, 1"
StaticArrays = "0.12, 1"
UnicodeGraphics = "0.1, 0.2"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDAKernels = "72cfdca4-0801-4ab0-bf6a-d52aa10adc57"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Aqua", "BenchmarkTools", "CUDAKernels", "SafeTestsets", "Unitful"]
