name = "Stencils"
uuid = "264155e8-78a8-466a-aa59-c9b28c34d21a"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.2.4"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UnicodeGraphics = "ebadf6b4-db70-5817-83da-4a19ad584e34"

[compat]
Adapt = "3, 4"
Aqua = "0.8"
BenchmarkTools = "1"
ConstructionBase = "1"
Dates = "0.1, 1"
KernelAbstractions = "0.9"
LinearAlgebra = "0.1, 1"
Random = "1"
SafeTestsets = "0.1"
SparseArrays = "0.1, 1"
StaticArrays = "1"
Statistics = "1"
Test = "1"
UnicodeGraphics = "0.2"
Unitful = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Aqua", "BenchmarkTools", "SafeTestsets", "Statistics", "Test", "Unitful"]
